'use strict';
const c=document.getElementById('game'),ctx=c.getContext('2d');const $=id=>document.getElementById(id);
const W=700,H=1080;let dpr=1;function resize(){dpr=Math.min(devicePixelRatio||1,2);c.width=W*dpr;c.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
const scoreEl=$('score'),bestEl=$('best'),ballsEl=$('balls'),multiEl=$('multi'),modeEl=$('mode'),modeText=$('modeText'),backMode=$('backMode');const shots={L:$('shotL'),R:$('shotR'),T:$('shotT'),S:$('shotS')};
let score=0,best=+localStorage.getItem('neonRushBestV5')||0,balls=3,multi=1,playing=false,paused=false,audioOn=true,last=0,shake=0,mode='ramps',combo=0,comboTimer=0,ballSave=0,multiball=0;
const input={L:false,R:false,launch:false};
const ball={x:600,y:1000,vx:0,vy:0,r:10,launched:false};const extras=[];
const fl={L:{x:250,y:1000,len:125,rest:-.42,up:-1.02,a:-.42},R:{x:450,y:1000,len:125,rest:Math.PI+.42,up:Math.PI+1.02,a:Math.PI+.42},U:{x:350,y:825,len:90,rest:-.18,up:-1.0,a:-.18}};
const bumpers=[{x:260,y:250,r:43,v:150},{x:350,y:195,r:48,v:200},{x:440,y:250,r:43,v:150},{x:300,y:365,r:32,v:100},{x:400,y:365,r:32,v:100}];
const targets=[{x:225,y:490,down:false,v:300},{x:350,y:470,down:false,v:400},{x:475,y:490,down:false,v:300}];const ramps=[{x:105,y:445,w:170,h:220,done:false,color:'#ff4fd8'},{x:425,y:445,w:170,h:220,done:false,color:'#65eaff'}];const particles=[];const spinner={x:350,y:615,hits:0,rot:0,flash:0};const scoop={x:350,y:735,r:34,lit:false,flash:0};
const walls=[{x1:72,y1:85,x2:72,y2:890},{x1:72,y1:85,x2:628,y2:85},{x1:628,y1:85,x2:628,y2:1000},{x1:72,y1:890,x2:170,y2:1050},{x1:628,y1:890,x2:530,y2:1050},{x1:170,y1:1050,x2:240,y2:1000},{x1:530,y1:1050,x2:460,y2:1000},{x1:300,y1:1040,x2:330,y2:1015},{x1:400,y1:1040,x2:370,y2:1015}];
function fmt(n){return String(Math.floor(n)).padStart(7,'0')}function hud(){scoreEl.textContent=fmt(score);bestEl.textContent=fmt(best);ballsEl.textContent=balls;multiEl.textContent='x'+multi;shots.L.className=ramps[0].done?'on':'';shots.R.className=ramps[1].done?'on':'';shots.T.className=targets.every(t=>t.down)?'on':'';shots.S.className=spinner.hits>=5?'on':'';const m=modeLabel();modeEl.textContent=m[0];modeText.textContent=m[1];backMode.textContent=m[0]}
function modeLabel(){return mode==='ramps'?['SHOOT THE RAMPS','Completa las dos rampas para encender el LOCK.']:mode==='targets'?['CLEAR TARGET BANK','Derriba los 3 targets para subir el multiplicador.']:mode==='lock'?['SHOOT THE SCOOP','El scoop central está iluminado.']:mode==='multi'?['MULTIBALL','Mantén las bolas vivas y busca jackpots.']:['JACKPOT LIT','Carga el jackpot con rampas y spinner.']}
function setMode(m){mode=m;hud()}function beep(f=320,d=.04,type='square'){if(!audioOn)return;try{const A=window.AudioContext||webkitAudioContext,a=new A(),o=a.createOscillator(),g=a.createGain();o.type=type;o.frequency.value=f;g.gain.value=.018;o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+d);setTimeout(()=>a.close(),d*1000+50)}catch(e){}}
function add(n){let v=Math.round(n*multi);score+=v;combo++;comboTimer=150;if(score>best){best=score;localStorage.setItem('neonRushBestV5',best)}if(n>=500)textPop(ball.x,ball.y,'+'+v,'#65eaff');hud()}
function textPop(x,y,t,col){particles.push({x,y,t,col,life:1})}function resetBall(){ball.x=600;ball.y=1000;ball.vx=0;ball.vy=0;ball.launched=false}function resetTable(){ramps.forEach(r=>r.done=false);targets.forEach(t=>t.down=false);spinner.hits=0;spinner.rot=0;scoop.lit=false;multiball=0;extras.length=0;setMode('ramps');resetBall()}
function newGame(){score=0;balls=3;multi=1;combo=0;comboTimer=0;playing=true;paused=false;resetTable();$('startOverlay').classList.add('hidden');$('pauseOverlay').classList.add('hidden');beep(520,.08,'triangle')}
function launch(){if(!playing||paused||ball.launched)return;ball.launched=true;ball.vx=-.5;ball.vy=-15.8;beep(650,.06);textPop(ball.x,ball.y,'LAUNCH','#65eaff')}
function drain(){if(ballSave){ballSave=0;resetBall();return}balls--;multi=1;combo=0;hud();if(balls<=0){playing=false;setTimeout(()=>{$('startOverlay').classList.remove('hidden');$('start').innerHTML='JUGAR DE NUEVO <small>TOCA PARA EMPEZAR</small>'},350);beep(70,.25,'sawtooth')}else resetBall()}
function nearest(px,py,x1,y1,x2,y2){let vx=x2-x1,vy=y2-y1,wx=px-x1,wy=py-y1,l=vx*vx+vy*vy,t=l?Math.max(0,Math.min(1,(wx*vx+wy*vy)/l)):0,x=x1+t*vx,y=y1+t*vy;return {x,y,nx:px-x,ny:py-y,d:Math.hypot(px-x,py-y)}}
function bounceSeg(s,restitution=.9){let q=nearest(ball.x,ball.y,s.x1,s.y1,s.x2,s.y2);if(q.d<ball.r+2){let d=q.d||1,nx=q.nx/d,ny=q.ny/d;ball.x=q.x+nx*(ball.r+2);ball.y=q.y+ny*(ball.r+2);let vn=ball.vx*nx+ball.vy*ny;if(vn<0){ball.vx-=1.9*vn*nx;ball.vy-=1.9*vn*ny;ball.vx*=restitution;ball.vy*=restitution;beep(180,.018)}}}
function circleHit(o,boost=1){let dx=ball.x-o.x,dy=ball.y-o.y,d=Math.hypot(dx,dy),min=ball.r+o.r;if(d<min){let n=d||1;dx/=n;dy/=n;ball.x=o.x+dx*(min+1);ball.y=o.y+dy*(min+1);let v=ball.vx*dx+ball.vy*dy;if(v<0){ball.vx-=2*v*dx;ball.vy-=2*v*dy}ball.vx+=dx*boost;ball.vy+=dy*boost;add(o.v||100);shake=4;return true}return false}
function flipperHit(f,key){let active=input[key];f.a+=((active?f.up:f.rest)-f.a)*.28;let ex=f.x+Math.cos(f.a)*f.len,ey=f.y+Math.sin(f.a)*f.len,q=nearest(ball.x,ball.y,f.x,f.y,ex,ey);if(q.d<ball.r+10&&ball.y<f.y+25){let nx=(ball.x-q.x)/(q.d||1),ny=(ball.y-q.y)/(q.d||1);ball.x=q.x+nx*(ball.r+11);ball.y=q.y+ny*(ball.r+11);let kick=active?12:5;ball.vx+=nx*kick;ball.vy+=ny*kick- (active?7:2);if(active)beep(280,.025)}}
function rampHit(r,i){let inBox=ball.x>r.x&&ball.x<r.x+r.w&&ball.y>r.y&&ball.y<r.y+r.h;if(inBox&&ball.vy<0&&!r.done){r.done=true;add(900);textPop(ball.x,ball.y,'RAMP!','#fff');beep(760,.07,'triangle');if(ramps.every(x=>x.done)){scoop.lit=true;setMode('lock')}}}
function targetHit(t){if(t.down)return; if(ball.x>t.x-20&&ball.x<t.x+20&&ball.y>t.y-28&&ball.y<t.y+28&&Math.abs(ball.vy)>1){t.down=true;add(t.v);beep(540,.035);if(targets.every(x=>x.down)){multi=Math.min(5,multi+1);setMode('lock');textPop(350,450,'MULTI UP','#ffd76a')}}}
function scoopHit(){if(!scoop.lit)return;let d=Math.hypot(ball.x-scoop.x,ball.y-scoop.y);if(d<ball.r+scoop.r){scoop.lit=false;add(2000);beep(900,.1,'triangle');setMode('multi');multiball=1;for(let i=0;i<2;i++)extras.push({x:350+i*18,y:700,vx:(i?2.3:-2.3),vy:-8,r:9,life:1})}}
function extraPhysics(b){b.vy+=.42;b.x+=b.vx;b.y+=b.vy;if(b.x<85||b.x>615){b.vx*=-.9;b.x=Math.max(85,Math.min(615,b.x))}if(b.y<95)b.vy=Math.abs(b.vy)*.92;if(b.y>1045){b.life=0;return}for(const o of bumpers){let dx=b.x-o.x,dy=b.y-o.y,d=Math.hypot(dx,dy),m=b.r+o.r;if(d<m){dx/=d||1;dy/=d||1;b.x=o.x+dx*m;b.y=o.y+dy*m;b.vx+=dx*5;b.vy+=dy*5;add(o.v)}}}
function physics(dt){let s=dt;bumpers.forEach(o=>o.pulse=Math.max(0,(o.pulse||0)-.06*s));spinner.flash=Math.max(0,spinner.flash-.07*s);scoop.flash=Math.max(0,scoop.flash-.06*s);ball.vy+=.48*s;if(!ball.launched){if(input.launch)launch();return}ball.x+=ball.vx*s;ball.y+=ball.vy*s;ball.vx*=.999;ball.vy*=.999;for(const w of walls)bounceSeg(w,.92);for(const o of bumpers)circleHit(o,4);for(const t of targets)targetHit(t);for(let i=0;i<ramps.length;i++)rampHit(ramps[i],i);scoopHit();
if(ball.x>325&&ball.x<375&&ball.y>590&&ball.y<640&&Math.abs(ball.vx)>1){spinner.hits++;spinner.rot+=.8;spinner.flash=1;add(125);if(spinner.hits>=5){spinner.hits=0;multi=Math.min(5,multi+1);add(1000);setMode('jackpot')}}
flipperHit(fl.L,'L');flipperHit(fl.R,'R');flipperHit(fl.U,'L');
for(let i=extras.length-1;i>=0;i--){extraPhysics(extras[i]);if(!extras[i].life)extras.splice(i,1)}
if(ball.y>1065)drain();if(comboTimer>0)comboTimer-=s;else combo=0;if(shake>0)shake-=.3*s;for(const p of particles){p.y-=.5*s;p.life-=.018*s}}
function glow(color){ctx.shadowBlur=18;ctx.shadowColor=color}
function rail(s,col='#7086a4',w=8){ctx.strokeStyle=col;ctx.lineWidth=w;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(s.x1,s.y1);ctx.lineTo(s.x2,s.y2);ctx.stroke();ctx.shadowBlur=0}
function drawFl(f,col){let ex=f.x+Math.cos(f.a)*f.len,ey=f.y+Math.sin(f.a)*f.len;ctx.save();glow(col);ctx.strokeStyle=col;ctx.lineWidth=24;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(f.x,f.y);ctx.lineTo(ex,ey);ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle='#09101c';ctx.beginPath();ctx.arc(f.x,f.y,11,0,Math.PI*2);ctx.fill();ctx.restore()}
function draw(){ctx.clearRect(0,0,W,H);const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#08172a');g.addColorStop(.45,'#07111e');g.addColorStop(1,'#02050a');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);
// printed playfield
ctx.fillStyle='#07101b';ctx.fillRect(45,45,610,990);ctx.globalAlpha=.15;for(let y=55;y<1035;y+=28){ctx.fillStyle='#1b3550';ctx.fillRect(50,y,600,1)}ctx.globalAlpha=1;
// physical outer walls
ctx.save();glow('#65eaff');ctx.strokeStyle='#253d5b';ctx.lineWidth=20;ctx.beginPath();ctx.moveTo(72,85);ctx.lineTo(72,890);ctx.lineTo(170,1050);ctx.lineTo(240,1000);ctx.moveTo(628,85);ctx.lineTo(628,890);ctx.lineTo(530,1050);ctx.lineTo(460,1000);ctx.moveTo(72,85);ctx.lineTo(628,85);ctx.stroke();ctx.shadowBlur=0;ctx.strokeStyle='#5a7596';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(72,85);ctx.lineTo(72,890);ctx.lineTo(170,1050);ctx.lineTo(240,1000);ctx.moveTo(628,85);ctx.lineTo(628,890);ctx.lineTo(530,1050);ctx.lineTo(460,1000);ctx.moveTo(72,85);ctx.lineTo(628,85);ctx.stroke();ctx.restore();
// launch lane, clearly separated
ctx.fillStyle='#0b1625';ctx.strokeStyle='#2b4765';ctx.lineWidth=3;ctx.beginPath();ctx.roundRect(560,730,58,300,18);ctx.fill();ctx.stroke();ctx.fillStyle='#5c6e86';ctx.font='8px system-ui';ctx.textAlign='center';ctx.fillText('PLUNGER LANE',589,755);ctx.strokeStyle='#65eaff';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(570,780);ctx.lineTo(570,1000);ctx.stroke();
// top lanes / ramps
ctx.strokeStyle='#ff4fd8';ctx.lineWidth=14;ctx.beginPath();ctx.moveTo(105,410);ctx.bezierCurveTo(105,120,220,100,270,210);ctx.stroke();ctx.strokeStyle='#65eaff';ctx.beginPath();ctx.moveTo(595,410);ctx.bezierCurveTo(595,120,480,100,430,210);ctx.stroke();ctx.lineWidth=3;ctx.strokeStyle='#9aabc0';ctx.beginPath();ctx.moveTo(120,410);ctx.bezierCurveTo(120,145,220,130,260,215);ctx.moveTo(580,410);ctx.bezierCurveTo(580,145,480,130,440,215);ctx.stroke();
// center art
ctx.fillStyle='#0c2034';ctx.strokeStyle='#315171';ctx.lineWidth=2;ctx.beginPath();ctx.roundRect(255,100,190,62,15);ctx.fill();ctx.stroke();ctx.fillStyle='#65eaff';ctx.font='900 20px system-ui';ctx.fillText('NEON RUSH',350,130);ctx.fillStyle='#61718a';ctx.font='7px system-ui';ctx.fillText('CITY AFTER DARK',350,147);
// bumpers
for(let i=0;i<bumpers.length;i++){let o=bumpers[i];ctx.save();let col=i===1?'#ff4fd8':'#65eaff';glow(col);ctx.fillStyle='#0d1d30';ctx.strokeStyle=col;ctx.lineWidth=7;ctx.beginPath();ctx.arc(o.x,o.y,o.r,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle='#dffaff';ctx.beginPath();ctx.arc(o.x,o.y,8,0,Math.PI*2);ctx.fill();ctx.restore()}
// target bank
ctx.fillStyle='#0a1625';ctx.strokeStyle='#38516e';ctx.lineWidth=3;ctx.beginPath();ctx.roundRect(170,430,360,85,18);ctx.fill();ctx.stroke();ctx.fillStyle='#637691';ctx.font='7px system-ui';ctx.fillText('TARGET BANK',350,445);targets.forEach(t=>{ctx.save();ctx.translate(t.x,t.y);ctx.fillStyle=t.down?'#263344':'#ff4fd8';glow(t.down?'#263344':'#ff4fd8');ctx.fillRect(-12,-20,24,40);ctx.shadowBlur=0;ctx.fillStyle='#fff';ctx.font='bold 9px system-ui';ctx.fillText(t.down?'X':'●',0,4);ctx.restore()});
// spinner
ctx.save();glow('#ffd76a');ctx.strokeStyle=spinner.flash?'#fff':'#ffd76a';ctx.lineWidth=6;ctx.beginPath();ctx.arc(350,615,34,0,Math.PI*2);ctx.stroke();ctx.translate(350,615);ctx.rotate(spinner.rot);ctx.strokeStyle='#fff';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(-26,0);ctx.lineTo(26,0);ctx.stroke();ctx.restore();ctx.fillStyle='#ffd76a';ctx.font='7px system-ui';ctx.fillText('SPINNER',350,660);
// scoop
ctx.save();glow(scoop.lit?'#ffd76a':'#475b76');ctx.fillStyle='#02060b';ctx.strokeStyle=scoop.lit?'#ffd76a':'#475b76';ctx.lineWidth=7;ctx.beginPath();ctx.arc(350,735,34,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle=scoop.lit?'#fff':'#6b7c93';ctx.font='900 9px system-ui';ctx.fillText(scoop.lit?'LOCK LIT':'SCOOP',350,738);ctx.restore();
// slingshots
rail({x1:145,y1:800,x2:225,y2:850},'#ff4fd8',17);rail({x1:555,y1:800,x2:475,y2:850},'#65eaff',17);
// inlanes/outlanes
rail({x1:155,y1:900,x2:215,y2:1000},'#ff4fd8',8);rail({x1:545,y1:900,x2:485,y2:1000},'#65eaff',8);rail({x1:215,y1:1000,x2:260,y2:975},'#607994',7);rail({x1:485,y1:1000,x2:440,y2:975},'#607994',7);
// center drain separator: physical posts create gap
ctx.fillStyle='#16243a';ctx.strokeStyle='#65eaff';ctx.lineWidth=3;ctx.beginPath();ctx.arc(300,1035,12,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.beginPath();ctx.arc(400,1035,12,0,Math.PI*2);ctx.fill();ctx.stroke();
// flippers separated by wide center gap
drawFl(fl.L,'#ff4fd8');drawFl(fl.R,'#65eaff');drawFl(fl.U,'#a76cff');
// ball
function db(b,col='#fff'){ctx.save();glow(col);const gr=ctx.createRadialGradient(b.x-3,b.y-4,1,b.x,b.y,b.r);gr.addColorStop(0,'#fff');gr.addColorStop(.5,col);gr.addColorStop(1,'#52647d');ctx.fillStyle=gr;ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,Math.PI*2);ctx.fill();ctx.restore()}db(ball);extras.forEach(b=>db(b,'#ffd76a'));
// plunger ball marker when waiting
if(!ball.launched){ctx.save();ctx.globalAlpha=.55;ctx.strokeStyle='#65eaff';ctx.setLineDash([5,6]);ctx.beginPath();ctx.arc(ball.x,ball.y,15,0,Math.PI*2);ctx.stroke();ctx.restore();ctx.fillStyle='#65eaff';ctx.font='900 8px system-ui';ctx.fillText('HOLD LAUNCH',600,1020)}
particles.forEach(p=>{ctx.save();ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle=p.col;ctx.font='900 13px system-ui';ctx.textAlign='center';ctx.fillText(p.t,p.x,p.y);ctx.restore()});
if(combo>1){ctx.save();ctx.textAlign='center';ctx.fillStyle='#ffd76a';ctx.font='900 14px system-ui';ctx.fillText('COMBO ×'+combo,350,680);ctx.restore()}}
function render(){ctx.save();if(shake>0)ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);draw();ctx.restore()}
function loop(t){let dt=Math.min(2.2,(t-last)/16.67||1);last=t;if(playing&&!paused)physics(dt);render();requestAnimationFrame(loop)}
function hold(el,key){const down=e=>{e.preventDefault();input[key]=true};const up=e=>{e.preventDefault();input[key]=false};['pointerdown','touchstart'].forEach(x=>el.addEventListener(x,down,{passive:false}));['pointerup','pointercancel','pointerleave','touchend','touchcancel'].forEach(x=>el.addEventListener(x,up,{passive:false}))}
hold($('flLeft'),'L');hold($('flRight'),'R');hold($('plunger'),'launch');
function tap(el,fn){let guard=0;const run=e=>{e.preventDefault();if(performance.now()-guard<350)return;guard=performance.now();fn()};el.addEventListener('pointerup',run,{passive:false});el.addEventListener('click',run)}tap($('start'),newGame);tap($('pause'),()=>{if(playing){paused=!paused;$('pauseOverlay').classList.toggle('hidden',!paused);$('pause').textContent=paused?'▶ RESUME':'Ⅱ PAUSE'}});tap($('sound'),()=>{audioOn=!audioOn;$('sound').textContent=audioOn?'🔊 SOUND':'🔇 MUTED'});tap($('newGame'),newGame);
addEventListener('keydown',e=>{if(e.key==='ArrowLeft')input.L=true;if(e.key==='ArrowRight')input.R=true;if(e.key==='ArrowUp')fl.U.a=fl.U.up;if(e.code==='Space')input.launch=true;if(e.key.toLowerCase()==='p'&&playing){paused=!paused;$('pauseOverlay').classList.toggle('hidden',!paused)}});addEventListener('keyup',e=>{if(e.key==='ArrowLeft')input.L=false;if(e.key==='ArrowRight')input.R=false;if(e.key==='ArrowUp')fl.U.a=fl.U.rest;if(e.code==='Space')input.launch=false});
// Start screen is deliberately robust on iPad: tapping the card also starts.
$('startOverlay').addEventListener('pointerup',e=>{if(e.target.closest('#start'))return;newGame()},{passive:false});
hud();requestAnimationFrame(loop);
